CREATE TABLE [dbo].[CUSTOMERS]
(
	--[Id] INT NOT NULL PRIMARY KEY
	CUSTOMERS nvarchar(50) constraint 
	CUSTOMERS_LOGIN primary key,
	CUSTOMERS_PASSWORD nvarchar(20) NOT NULL,
	CUSTOMERS_SURNAME  nvarchar(20) NOT NULL, 
	CUSTOMERS_NAME  nvarchar(20) NOT NULL, 
	CUSTOMERS_CART nvarchar(20) NOT NULL,
	CUSTOMERS_CONTACTS nvarchar(100) NOT NULL
)

